# Generated by Django 3.1.2 on 2021-04-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medorganization',
            name='in_stock',
        ),
    ]
