# Generated by Django 3.1.2 on 2021-04-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_medorganization_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medorganization',
            name='rooms',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
