# Generated by Django 3.1.2 on 2021-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_medorganization_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='medorganization',
            name='type_1_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medorganization',
            name='type_2_stock',
            field=models.BooleanField(default=True),
        ),
    ]
