# Generated by Django 3.1.2 on 2021-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210410_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='medorganization',
            name='extra',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medorganization',
            name='phone_number',
            field=models.CharField(max_length=128),
        ),
    ]
