# Generated by Django 3.1.2 on 2021-05-05 15:15

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210421_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='medorganization',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medorganization',
            name='contact_information',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medorganization',
            name='documents_needed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medorganization',
            name='extra',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medorganization',
            name='photo',
            field=models.ImageField(null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='vaccme'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='medorganization',
            name='rayon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
