# Generated by Django 3.1.2 on 2021-04-21 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210421_0135'),
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatContext',
        ),
    ]
